.editorconfig
src/main.js

add the same editorConfig as we use in brewskeyAdmin

add editorConfig

---

.editorconfig
package.json
src/main.js
src/views/api_v1.js

1) clean as much depreciation errors as I could find. there is  a big chance that there many more errors, will fix them when find.
2) rewrite main.js in es6 style.
seems  "node-oauth2-server"  doen't works right in the current version of server, and checks nothing.. that way we can do whatever we want from particle-cli with any auth_token provided.

Update express & rewrite main.js to es6

---

package.json

hogan-express is a template engine and its never used in the project.

Remove hogan

---

.eslintignore
.eslintrc
package.json

if this okey, I'll also add the same to spark-protocol

add eslint

---

src/lib/RouteConfig.js

there're still some flow errors, but anyways.

fix routeConfig, add some annotations

---

package.json
src/lib/PasswordHasher.js
src/lib/RolesController.js

just start digging. its a very first step

Oauth start

---

package.json
src/lib/controllers/DevicesController.js
src/lib/repository/DeviceRepository.js
src/types.js

https://github.com/facebook/flow/releases/tag/v0.37.0

update flowbin / merge master

---

.gitignore
package.json
src/app.js
src/controllers/DevicesController.js
src/repository/DeviceFirmwareFileRepository.js
src/repository/DeviceRepository.js
src/settings.js
src/types.js
test/setup/settings.js

I've  added all know app logic inside spark-server. And remove `FlashKnown` message from sparkCore. I strongly believe that it should be there.

implement known_apps

---

src/RouteConfig.js
src/app.js
src/controllers/EventsController.js
src/views/EventViews001.js
src/views/api_v1.js

Looking on all that `void` functions with tons of side effects stuff, I start to realize how actually beautiful functional programming is..Here, Its really hard to understand what all functions actually do(same in flasher btw, like this._prepare(), this._beginUpdate(),)...
Anyways, I  partly moved stuff to controller, all of this still in progress.
1) getEvents stream works, but only when I do it for the first time. I mean start the server, `particle subscribe` - it gets events..then try `particle subscrib` it doesn't...(same behavior in their code). My first thoughts were that it something about sockets id or sockets clean up, but seems not.
2)  sendEvents - works, but implementation dirty as hell.

working on events. partly move eventViews to controller with the same  implementation.

---

src/controllers/EventsController.js
src/managers/EventManager.js

I need filtering in Publisher level, to be able to make device <-> device connection with `MY_DEVICE` option. so moved it there.

move events filtering to EventPublisher

---

.babelrc
package.json

and remove babel-polyfill from package.json and from ava babel setup(no needs anymore). Closes #52

add babel-plugin-transform-runtime

---

package.json
src/controllers/WebhooksController.js
src/repository/UserFileRepository.js
src/repository/WebhookFileRepository.js
test/DevicesController.test.js
test/ProvisioningController.test.js
test/UsersController.test.js
test/WebhooksController.test.js

, use it in webhookFileRepo/userFileRepository, fix some Flow and add missing async

add uuid package

---

src/main.js

in pair with: https://github.com/Brewskey/spark-protocol/pull/25

add deviceKeyRepository to deviceServerConfig

---

src/controllers/DeviceClaimsController.js
src/defaultBindings.js
src/repository/DeviceRepository.js
src/repository/UserFileRepository.js
src/types.js

You have to recreate `user`, for all these work as expected, because I added  `ClaimCodes: Array<string>` to the model.
the pr in pair with: https://github.com/Brewskey/spark-protocol/pull/30

implement particle setup

---

package.json
src/controllers/EventsController.js
src/managers/WebhookManager.js
src/types.js

all in one method..not for merging, just for review

implement base hogan templates and response events.

---

src/controllers/EventsController.js
src/managers/EventManager.js

with https://github.com/Brewskey/spark-protocol/pull/39/

fix: rename eventName to eventNamePrefix in eventController

---

src/controllers/EventsController.js

Closes https://github.com/Brewskey/spark-server/issues/94

fix eventsController endpoints routes

---

src/settings.js

Closes https://github.com/Brewskey/spark-server/issues/107

move data folder

---

dist/managers/WebhookManager.js
dist/settings.js
src/managers/WebhookManager.js

the buffer was transformed with photons right way, but in the event stream we saw this instead of actual data string:

transform webhookResponse buffer chunks to string

---

README.md

fix typo in install instructions

---

src/main.js
src/settings.js
src/types.js
test/setup/settings.js

closes https://github.com/Brewskey/spark-server/issues/135

add ssl support

---

dist/defaultBindings.js
dist/lib/promisify.js
dist/main.js
dist/managers/WebhookManager.js
dist/repository/TingoDb.js
dist/repository/UserDatabaseRepository.js
dist/repository/WebhookDatabaseRepository.js
dist/settings.js
package.json
src/defaultBindings.js
src/lib/promisify.js
src/repository/TingoDb.js
src/repository/UserDatabaseRepository.js
src/repository/WebhookDatabaseRepository.js
src/settings.js
src/types.js
test/setup/settings.js

Closes https://github.com/Brewskey/spark-server/issues/136

add tingodb, implement database repositories

---

dist/scripts/migrateFilesToDatabase.js
dist/settings.js
package.json
src/scripts/migrateFilesToDatabase.js
src/settings.js
src/types.js
test/setup/settings.js

Closes https://github.com/Brewskey/spark-server/issues/143

add migrateScript

---

dist/managers/DeviceManager.js
src/managers/DeviceManager.js
test/DevicesController.test.js

Closes https://github.com/Brewskey/spark-server/issues/156

throw an error if device is already claimed by the user

---

dist/defaultBindings.js
dist/repository/BaseMongoDb.js
dist/repository/DeviceKeyDatabaseRepository.js
src/defaultBindings.js
src/repository/DeviceKeyDatabaseRepository.js
src/types.js
test/DeviceClaimsController.test.js
test/DevicesController.test.js
test/ProvisioningController.test.js

with https://github.com/Brewskey/spark-protocol/pull/99
Closes https://github.com/Brewskey/spark-server/issues/155

implement deviceKeyDatabase repo

---

dist/managers/DeviceManager.js
dist/repository/DeviceKeyDatabaseRepository.js
src/managers/DeviceManager.js
src/repository/DeviceKeyDatabaseRepository.js
src/types.js

in pair with https://github.com/Brewskey/spark-protocol/pull/101

made deviceKeyRepository consistent with IBaseRepository

---

package.json
src/OAuthModel.js
src/RouteConfig.js
src/controllers/DeviceClaimsController.js
src/controllers/DevicesController.js
src/controllers/WebhooksController.js
src/defaultBindings.js
src/lib/utils.js
src/managers/DeviceManager.js
src/managers/PermissionManager.js
src/managers/WebhookManager.js
src/oauthClients.json
src/repository/BaseMongoDb.js
src/repository/DeviceAttributeDatabaseRepository.js
src/repository/UserDatabaseRepository.js
src/repository/UserFileRepository.js
src/repository/WebhookDatabaseRepository.js
src/settings.js
src/types.js
test/DevicesController.test.js
test/WebhookManager.test.js
test/setup/settings.js

didn't include build files, because the diff is a big mess even without those.

implement Administrator permissions first try

---

dist/scripts/migrateFilesToDatabase.js
src/scripts/migrateFilesToDatabase.js

Closes https://github.com/Brewskey/spark-server/issues/160

add deviceKeys migration to migrateScript

---

examples/azure-mongodb.js
package-lock.json

Closes https://github.com/Brewskey/spark-server/issues/172.
with that commit : https://github.com/Brewskey/spark-protocol/commit/109141fdf255de47c597f3689d0225a421d2393c

Fix package lock

---

examples/docker/production/Dockerfile
examples/docker/readme.md

Hi, 
I've added a Docker Script and documentation inside /example to build a Spark-Server Docker image

Added a Docker Build Script and Explanation

---

.vscode/settings.json

Add a configuration in directory .vscode so the Repository can be opened and used in "visualstudio code"
Note: you have to add a Flow Package to activate Checks and Support in vscode!

add configuration to be compatible with VisualStudioCode

---

dist/controllers/DevicesController.js
dist/controllers/EventsController.js
dist/defaultBindings.js
dist/managers/DeviceManager.js
dist/managers/EventManager.js
dist/managers/WebhookManager.js
src/controllers/DevicesController.js
src/defaultBindings.js
src/managers/DeviceManager.js
src/managers/EventManager.js
src/managers/WebhookManager.js
src/types.js
test/DeviceClaimsController.test.js
test/DevicesController.test.js
test/ProvisioningController.test.js

Merge this and that https://github.com/Brewskey/spark-protocol/pull/100 together at one time, or it will break all the things.
Closes https://github.com/Brewskey/spark-server/issues/175
Closes https://github.com/Brewskey/spark-server/issues/169

publishAndListenForResponse

---

dist/managers/PermissionManager.js
package-lock.json
src/controllers/DevicesController.js
src/lib/deviceToAPI.js
src/managers/DeviceManager.js
src/managers/PermissionManager.js
src/repository/UserDatabaseRepository.js
src/types.js
test/DeviceClaimsController.test.js
test/DevicesController.test.js
test/ProvisioningController.test.js

with https://github.com/Brewskey/spark-protocol/pull/110

use getAttributes for devices from device-server.

---

dist/scripts/migrateFilesToDatabase.js
src/scripts/migrateFilesToDatabase.js

closes https://github.com/Brewskey/spark-server/issues/232

update migrateScript, so it saves dates correctly.

---

dist/repository/DeviceAttributeDatabaseRepository.js
src/repository/DeviceAttributeDatabaseRepository.js

closes https://github.com/Brewskey/spark-server/issues/237

stringify device variables

---

dist/repository/DeviceAttributeDatabaseRepository.js
src/repository/DeviceAttributeDatabaseRepository.js

Closes https://github.com/Brewskey/spark-server/issues/241

fix variables loss on update device name.

---

dist/controllers/DevicesController.js
dist/managers/DeviceManager.js
src/controllers/DevicesController.js
src/managers/DeviceManager.js

https://docs.particle.io/reference/api/#ping-a-device
Seems we need to fix our payloads, like `connected -> online` etc..this can be breaking change for those who use the server though.

add pingDevice endpoint

---

dist/RouteConfig.js
dist/controllers/EventsController.js
src/RouteConfig.js
src/controllers/EventsController.js

Closes https://github.com/Brewskey/spark-server/issues/247

return keep alive for event stream
